INSERT INTO EMPDETAILS (ID, NAME, DESIGNATION, DEPARTMENT, COMPANY_NAME) VALUES (1, 'John', 'SM', 'IT', 'INFY');
INSERT INTO EMPDETAILS (ID, NAME, DESIGNATION, DEPARTMENT, COMPANY_NAME) VALUES (2, 'Sarah', 'PO', 'IT', 'INFY');
INSERT INTO EMPDETAILS (ID, NAME, DESIGNATION, DEPARTMENT, COMPANY_NAME) VALUES (3, 'Paul', 'DEV', 'IT', 'INFY');
INSERT INTO EMPDETAILS (ID, NAME, DESIGNATION, DEPARTMENT, COMPANY_NAME) VALUES (4, 'Maria', 'SM', 'IT', 'TCS');
INSERT INTO EMPDETAILS (ID, NAME, DESIGNATION, DEPARTMENT, COMPANY_NAME) VALUES (5, 'Steve', 'PO', 'IT', 'TCS');
INSERT INTO EMPDETAILS (ID, NAME, DESIGNATION, DEPARTMENT, COMPANY_NAME) VALUES (6, 'Neil', 'DEV', 'IT', 'TCS');