CREATE TABLE IF NOT EXISTS EMPDETAILS (
ID NUMBER NOT NULL UNIQUE,
NAME VARCHAR (50) NOT NULL,
DESIGNATION VARCHAR (50) NOT NULL,
DEPARTMENT VARCHAR (50) NOT NULL,
COMPANY_NAME VARCHAR (50) NOT NULL
);